#[derive(Debug, Clone, Copy)]
pub struct Anchor {
    pub id: &'static str,
    pub host: &'static str,
    pub metro: &'static str,
    pub latitude: f64,
    pub longitude: f64,
}

impl Anchor {
    pub fn label(&self) -> String {
        format!("{} ({})", self.metro, self.id)
    }
}

pub const BUILTIN_ANCHORS: &[Anchor] = &[
    Anchor {
        id: "eu-central-1",
        host: "ec2.eu-central-1.amazonaws.com",
        metro: "Frankfurt",
        latitude: 50.1109,
        longitude: 8.6821,
    },
    Anchor {
        id: "eu-central-2",
        host: "ec2.eu-central-2.amazonaws.com",
        metro: "Zurich",
        latitude: 47.3769,
        longitude: 8.5417,
    },
    Anchor {
        id: "eu-south-1",
        host: "ec2.eu-south-1.amazonaws.com",
        metro: "Milan",
        latitude: 45.4642,
        longitude: 9.1900,
    },
    Anchor {
        id: "eu-south-2",
        host: "ec2.eu-south-2.amazonaws.com",
        metro: "Madrid",
        latitude: 40.4168,
        longitude: -3.7038,
    },
    Anchor {
        id: "eu-west-1",
        host: "ec2.eu-west-1.amazonaws.com",
        metro: "Dublin",
        latitude: 53.3498,
        longitude: -6.2603,
    },
    Anchor {
        id: "eu-west-2",
        host: "ec2.eu-west-2.amazonaws.com",
        metro: "London",
        latitude: 51.5072,
        longitude: -0.1276,
    },
    Anchor {
        id: "eu-west-3",
        host: "ec2.eu-west-3.amazonaws.com",
        metro: "Paris",
        latitude: 48.8566,
        longitude: 2.3522,
    },
    Anchor {
        id: "eu-north-1",
        host: "ec2.eu-north-1.amazonaws.com",
        metro: "Stockholm",
        latitude: 59.3293,
        longitude: 18.0686,
    },
    Anchor {
        id: "us-east-1",
        host: "ec2.us-east-1.amazonaws.com",
        metro: "Ashburn",
        latitude: 39.0438,
        longitude: -77.4874,
    },
    Anchor {
        id: "ca-central-1",
        host: "ec2.ca-central-1.amazonaws.com",
        metro: "Montreal",
        latitude: 45.5017,
        longitude: -73.5673,
    },
    Anchor {
        id: "us-west-2",
        host: "ec2.us-west-2.amazonaws.com",
        metro: "Portland",
        latitude: 45.5152,
        longitude: -122.6784,
    },
    Anchor {
        id: "ap-south-1",
        host: "ec2.ap-south-1.amazonaws.com",
        metro: "Mumbai",
        latitude: 19.0760,
        longitude: 72.8777,
    },
    Anchor {
        id: "ap-south-2",
        host: "ec2.ap-south-2.amazonaws.com",
        metro: "Hyderabad",
        latitude: 17.3850,
        longitude: 78.4867,
    },
    Anchor {
        id: "ap-southeast-1",
        host: "ec2.ap-southeast-1.amazonaws.com",
        metro: "Singapore",
        latitude: 1.3521,
        longitude: 103.8198,
    },
    Anchor {
        id: "ap-southeast-2",
        host: "ec2.ap-southeast-2.amazonaws.com",
        metro: "Sydney",
        latitude: -33.8688,
        longitude: 151.2093,
    },
    Anchor {
        id: "ap-east-1",
        host: "ec2.ap-east-1.amazonaws.com",
        metro: "Hong Kong",
        latitude: 22.3193,
        longitude: 114.1694,
    },
    Anchor {
        id: "ap-northeast-1",
        host: "ec2.ap-northeast-1.amazonaws.com",
        metro: "Tokyo",
        latitude: 35.6762,
        longitude: 139.6503,
    },
    Anchor {
        id: "ap-northeast-2",
        host: "ec2.ap-northeast-2.amazonaws.com",
        metro: "Seoul",
        latitude: 37.5665,
        longitude: 126.9780,
    },
    Anchor {
        id: "il-central-1",
        host: "ec2.il-central-1.amazonaws.com",
        metro: "Tel Aviv",
        latitude: 32.0853,
        longitude: 34.7818,
    },
    Anchor {
        id: "me-south-1",
        host: "ec2.me-south-1.amazonaws.com",
        metro: "Bahrain",
        latitude: 26.0667,
        longitude: 50.5577,
    },
    Anchor {
        id: "me-central-1",
        host: "ec2.me-central-1.amazonaws.com",
        metro: "Abu Dhabi",
        latitude: 24.4539,
        longitude: 54.3773,
    },
    Anchor {
        id: "sa-east-1",
        host: "ec2.sa-east-1.amazonaws.com",
        metro: "Sao Paulo",
        latitude: -23.5505,
        longitude: -46.6333,
    },
    Anchor {
        id: "mx-central-1",
        host: "ec2.mx-central-1.amazonaws.com",
        metro: "Queretaro",
        latitude: 20.5888,
        longitude: -100.3899,
    },
    Anchor {
        id: "af-south-1",
        host: "ec2.af-south-1.amazonaws.com",
        metro: "Cape Town",
        latitude: -33.9249,
        longitude: 18.4241,
    },
];
